### ISSUE TITLE
Console error during startup

### ISSUE THREAD

**Issue by Accelsnow** [MizarZh/mathlive-in-editor-mode#1]
During initial plugin loading, the following two errors appear in the console consistently:

![image](https://github.com/MizarZh/mathlive-in-editor-mode/assets/36573521/1b5f2e31-0bae-4e9f-b939-82fcfb14f3f7)

It does not appear to affect normal plugin functionality; the plugin seems to work as-intended.

---

Platform: Windows
Obsidian version: 1.6.3
Mathlive-in-editor-mode version: 0.1.5

**Comment by MizarZh** [comment]
> During initial plugin loading, the following two errors appear in the console consistently:
> 
> ![image](https://private-user-images.githubusercontent.com/36573521/340379501-1b5f2e31-0bae-4e9f-b939-82fcfb14f3f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMDQ3MzAsIm5iZiI6MTcxOTAwNDQzMCwicGF0aCI6Ii8zNjU3MzUyMS8zNDAzNzk1MDEtMWI1ZjJlMzEtMGJhZS00ZTlmLWI5MzktODJmY2ZiMTRmM2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDIxMTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NThmMWEzZjk5MjFkMmEyNDIxMmMyZmM0Y2VjZjFhYjEzYWEyOWZiNzU0NGQ1MWZhYTYwOTMyZDZlYjcwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m8vko1_vIua4XHtrQpfM1wVTM2utIpEhTWX3Y9LFN-U)
> 
> It does not appear to affect normal plugin functionality; the plugin seems to work as-intended.
> 
> Platform: Windows Obsidian version: 1.6.3 Mathlive-in-editor-mode version: 0.1.5

Yes it doesn't affect the functionality. Obsidian cannot import fonts via external files, but mathlive requires them. I work around it by using inline css fonts, but it's not the intended way for mathlive so these errors still exist.
